import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { redirect } from "next/navigation";
import Dashboard from "@/components/Dashboard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let isUserAuthenticated = true;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-svh w-full `}
      >
        <div className="sm:ml-96 sm:mr-96 p-4 text-xl flex flex-col gap-0.5">
          <div>Slack Clone AWS</div>
          <div className="text-sm flex flex-row">
            {isUserAuthenticated && (
              <div className="flex flex-row gap-2">
                <div>You are signed in as JohnDoe</div>
                <div className="bg-red-500 text-black text-xs px-4 py-0.5 border border-black hover:bg-red-400 cursor-pointer">
                  Sign out
                </div>
              </div>
            )}
          </div>
        </div>
        <div className="sm:ml-96 sm:mr-96 grow overflow-y-scroll max-h-full">
          {isUserAuthenticated ? <Dashboard /> : children}
        </div>
        <div className="sm:ml-96 sm:mr-96 flex flex-col p-1 ">
          <div>
            Slack Clone built with NextJS (frontend), NodeJS (backend), and AWS
            technologies.
          </div>
          <Link
            target="_blank"
            className="underline px-4 py-1 "
            href="https://github.com/sklawik/slack-clone-aws"
          >
            See the project on Github
          </Link>
        </div>
      </body>
    </html>
  );
}
